baseurl: "/Portfolio-site"
url: "https://fischerc-dev.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
